### ISSUE TITLE
Tests do not pass in "complete" projects - NoSuchBeanException in ViesVatValidatorFunctionTest

### ISSUE THREAD

**Issue by scottvlaminck** [micronaut-guides/micronaut-function-aws-lambda#6]
`ViesVatValidatorFunctionTest` fails in the "complete" projects with the following error: 

> example.micronaut.ViesVatValidatorFunctionTest > testViesVatValidatorFunction FAILED
>     io.micronaut.context.exceptions.NoSuchBeanException at ViesVatValidatorFunctionTest.java:17

It seems that `ViesVatValidatorClient` from src/test is not registered as a bean to be retrieved in the test via `server.getApplicationContext().getBean(ViesVatValidatorClient.class);`

**Comment by RajeshSamson** [comment]
I'm also facing the same issue? Do we have any alternative approach to execute the test case or do we need to provide any additional parameters?

**Comment by ilopmar** [comment]
Fixed with the latest changes in the guide.
